--SQL Advance Case Study

use [db_SQLCaseStudies]
--Q1--BEGIN 
SELECT DISTINCT [STATE] FROM FACT_TRANSACTIONS A
INNER JOIN DIM_LOCATION B ON A.IDLocation = B.IDLocation
INNER JOIN DIM_MODEL C ON A.IDModel = C.IDModel
WHERE [DATE] BETWEEN '2005-01-04' AND GETDATE();
--Q1--END

--Q2--BEGIN 

SELECT TOP 1 [STATE] ,COUNT(QUANTITY) AS QTY FROM FACT_TRANSACTIONS A 	
INNER JOIN DIM_LOCATION B ON A.IDLocation = B.IDLocation
INNER JOIN DIM_MODEL C ON A.IDModel = C.IDModel
INNER JOIN DIM_MANUFACTURER D ON C.IDManufacturer = D.IDManufacturer
WHERE COUNTRY = 'US' AND Manufacturer_Name = 'SAMSUNG'
GROUP BY [STATE] 
ORDER BY 2 DESC;

--Q2--END

--Q3--BEGIN   
SELECT MODEL_NAME , ZIPCODE, [STATE] , COUNT(IDCustomer) AS NO_OF_TRANSACTIONS
FROM FACT_TRANSACTIONS A
INNER JOIN DIM_LOCATION B ON A.IDLocation = B.IDLocation
INNER JOIN DIM_MODEL C ON A.IDModel = C.IDModel
GROUP BY Model_Name ,ZIPCODE , [STATE];

--Q3--END

--Q4--BEGIN 
SELECT TOP 1 MODEL_NAME , UNIT_PRICE 
FROM DIM_MODEL
ORDER BY 2 ;

--Q4--END

--Q5-- 
SELECT MODEL_NAME , AVG(TOTALPRICE) AS AVG_PRICE 
FROM DIM_MODEL T1
INNER JOIN DIM_MANUFACTURER T2 ON T1.IDManufacturer = T2.IDManufacturer
INNER JOIN FACT_TRANSACTIONS T3 ON T1.IDModel = T3.IDModel
WHERE Manufacturer_Name IN (
SELECT TOP 5 MANUFACTURER_NAME 
FROM FACT_TRANSACTIONS A 
INNER JOIN DIM_MODEL B ON  A.IDMODEL = B.IDMODEL
INNER JOIN DIM_MANUFACTURER C ON B.IDMANUFACTURER = C.IDMANUFACTURER
GROUP BY MANUFACTURER_NAME
ORDER BY SUM(QUANTITY) DESC ) 
GROUP BY Model_Name
ORDER BY 2 
--Q5--END

--Q6--BEGIN 6.	

SELECT CUSTOMER_NAME , AVG(TOTALPRICE) AS AVG 
FROM FACT_TRANSACTIONS T1 
INNER JOIN DIM_CUSTOMER T2 ON T1.IDCUSTOMER = T2.IDCUSTOMER
WHERE YEAR(DATE) = 2009
GROUP BY CUSTOMER_NAME
HAVING AVG(TOTALPRICE) > 500

--Q6--END
	
--Q7--BEGIN 
SELECT IDMODEL FROM (
    SELECT IDMODEL,
           RANK() OVER (PARTITION BY YEAR(Date) ORDER BY SUM(QUANTITY) DESC) AS RN
    FROM FACT_TRANSACTIONS
    WHERE YEAR(Date) IN (2008, 2009, 2010)
	GROUP BY YEAR(DATE), IDMODEL
) a
WHERE RN <= 5
GROUP BY IDMODEL
HAVING COUNT(*) = 3
--Q7--END	

--Q8--BEGIN 
SELECT MANUFACTURER_NAME , YEAR FROM (
SELECT
MANUFACTURER_NAME, SUM(TOTALPRICE) AS TOT_SALES, YEAR(DATE) AS YEAR,
ROW_NUMBER() OVER( ORDER BY SUM(TOTALPRICE) DESC ) AS RNUM2
FROM FACT_TRANSACTIONS A
INNER JOIN DIM_MODEL B ON A.IDMODEL = B.IDMODEL
INNER JOIN DIM_MANUFACTURER C ON B.IDMANUFACTURER =  C.IDMANUFACTURER 
WHERE YEAR(DATE) = 2009
GROUP BY MANUFACTURER_NAME , YEAR(DATE) 
) AS T2
WHERE
RNUM2 = 2
UNION ALL
SELECT MANUFACTURER_NAME , YEAR FROM (
SELECT
MANUFACTURER_NAME, SUM(TOTALPRICE) AS TOT_SALES, YEAR(DATE) AS YEAR,
ROW_NUMBER() OVER( ORDER BY SUM(TOTALPRICE) DESC ) AS RNUM2
FROM FACT_TRANSACTIONS A
INNER JOIN DIM_MODEL B ON A.IDMODEL = B.IDMODEL
INNER JOIN DIM_MANUFACTURER C ON B.IDMANUFACTURER =  C.IDMANUFACTURER 
WHERE YEAR(DATE) = 2010
GROUP BY MANUFACTURER_NAME , YEAR(DATE) 
) AS T2
WHERE
RNUM2 = 2;
--Q8--END

--Q9--BEGIN
SELECT MANUFACTURER_NAME 
FROM FACT_TRANSACTIONS A
INNER JOIN DIM_MODEL B ON A.IDMODEL = B.IDMODEL
INNER JOIN DIM_MANUFACTURER C ON B.IDMANUFACTURER =  C.IDMANUFACTURER 
WHERE YEAR(DATE) = 2010
GROUP BY MANUFACTURER_NAME 
EXCEPT
SELECT MANUFACTURER_NAME 
FROM FACT_TRANSACTIONS A
INNER JOIN DIM_MODEL B ON A.IDMODEL = B.IDMODEL
INNER JOIN DIM_MANUFACTURER C ON B.IDMANUFACTURER =  C.IDMANUFACTURER 
WHERE YEAR(DATE) = 2009
GROUP BY MANUFACTURER_NAME

--Q9--END

--Q10--BEGIN 
With TBL1 AS (
SELECT top 100 CUSTOMER_NAME , YEAR(DATE) AS YEAR , AVG(TOTALPRICE) AS AVG_Price , AVG(QUANTITY) AS AVG_QTY, SUM(TOTALPRICE) AS SPEND 
FROM FACT_TRANSACTIONS A
INNER JOIN DIM_CUSTOMER B ON A.IDCUSTOMER = B.IDCUSTOMER 
GROUP BY YEAR(DATE),CUSTOMER_NAME 
ORDER BY CUSTOMER_NAME , Year(Date) 
),
TBL2 AS (
SELECT *, 
	LAG(SPEND,1) OVER (PARTITION BY Customer_name ORDER BY Year) PREVIOUS_SPEND
FROM
	TBL1 )
SELECT * ,
	FORMAT(
		(SPEND - PREVIOUS_SPEND)  / PREVIOUS_SPEND,
		'P'
	) PRECENT_CHANGE
FROM
	TBL2;

--Q10--END
	